spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculations_channel:
          name: calculations_channel

jira:
  api:
    base-url: https://project1test.atlassian.net
    username: demonserker@gmail.com
    secret: ATATT3xFfGF0HWslAte2MJUZxmWHTnoIJA9Ib15S0nM3rXFoG1lUYhrOnPoEqkKcuxJpaWid-TvzPsgmu_ArxktJDetBdljSPFrtExPZoPJKvbfKia8ihAuV2JN2JgZKa4eodlxxl8Io6Gbi8EBAiX3PJaUJOK5BZXXVhQJU0HwSxmTLpzWoVM8=92339E1D
    issue-url: /rest/api/2/issue/

server:
  port: 8082

logging:
  level:
    root: info

calculations_messages_processing:
  enabled: true

services:
  s3:
    endpoint: http://localhost:9000
    accessKey: user
    secretKey: password
    bucketName: projectbucket
    isMocked: false
  payment-service:
    host: http://localhost
    port: 9080
  user-service:
    host: http://localhost
    port: 8080